name: Build and Release (Windows)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Initialize submodules
        run: |
          git submodule update --init --recursive

      - name: Use Python 3
        uses: shivammathur/setup-python@v3
        with:
          version: '3.11'  # Update with your desired Python version

      - name: Install dependencies (optional)
        run: |
          python -m pip install -r requirements.txt  # Replace with your requirements file if needed

      - name: Run build script
        run: |
          .\build.bat  # Assuming your bat file is named build.bat

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

      - name: Create Release
        uses: nlopes/release-action@v3.1.2
        with:
          tag_name: ${{ github.sha }}  # Creates a tag with commit SHA
          release_name: "Pre-Release ${{ github.sha }}"
          body: "Built from commit ${{ github.sha }}"
          draft: false  # Set to true for draft releases
          artifacts: "dist/*"
